# Generated by Django 3.0.3 on 2021-04-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvGeneratorBO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='github',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='gitlab',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='linkedin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
