# Generated by Django 3.0.3 on 2021-04-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvGeneratorBO', '0002_auto_20210410_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='dataManager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cvGeneratorBO.DataManager'),
            preserve_default=False,
        ),
    ]
