# Generated by Django 3.0.3 on 2021-04-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvGeneratorBO', '0003_info_datamanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='dataManager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='infos', to='cvGeneratorBO.DataManager'),
        ),
        migrations.AlterField(
            model_name='job',
            name='dataManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='cvGeneratorBO.DataManager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dataManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='cvGeneratorBO.DataManager'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cvGeneratorBO.Skillset'),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='dataManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skillsets', to='cvGeneratorBO.DataManager'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='cvGeneratorBO.Training'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='cvGeneratorBO.Project'),
        ),
        migrations.AlterField(
            model_name='training',
            name='dataManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='cvGeneratorBO.DataManager'),
        ),
    ]
