# Generated by Django 3.0.3 on 2021-04-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvGeneratorBO', '0007_auto_20210410_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.IntegerField(choices=[(1, 'Main'), (2, 'Secondary')], default=1),
        ),
    ]
