# Generated by Django 3.0.3 on 2021-04-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvGeneratorBO', '0008_auto_20210411_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='primary_font',
            field=models.CharField(choices=[('Lato', 'Lato'), ('Oswald', 'Oswald'), ('Ubuntu', 'Ubuntu'), ('Roboto', 'Roboto')], default='Ubuntu', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_font',
            field=models.CharField(choices=[('Lato', 'Lato'), ('Oswald', 'Oswald'), ('Ubuntu', 'Ubuntu'), ('Roboto', 'Roboto')], default='Ubuntu', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ternary_font',
            field=models.CharField(choices=[('Lato', 'Lato'), ('Oswald', 'Oswald'), ('Ubuntu', 'Ubuntu'), ('Roboto', 'Roboto')], default='Ubuntu', max_length=255),
        ),
    ]
