# Generated by Django 3.0.3 on 2021-04-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvGeneratorBO', '0013_auto_20210417_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='siteTitle',
        ),
    ]
